### ISSUE TITLE
Nice scaffold!

### ISSUE THREAD

**Issue by dgilperez** [nathan-andosen/firebase-cloud-functions-seed#5]
Hi! 

I found this project looking on best practices to build a codebase with cloud functions, and specially how to seed data. I'm fairly new to the ecosystem and to serverless. 

I wanted to thank you for sharing this, I peeked through the code and it looks like how I'd go about organizing code. 

And I also see the project didn't receive any attention for some time, so I wanted to ask: is this still relevant? did you go with this in your projects, or did you eventually decided for another approach? if you did the later, could you please point me in the right direction with some reference? 

Many thanks again!

**Comment by Jeremywhiteley** [comment]
This is hands down the best seed for Firebase Cloud functions.   It’s geared for spread.  I am using it and no issues at all.

**Comment by dgilperez** [comment]
Thanks a lot @Jeremywhiteley ! Getting already some nice ideas out of this.
